"""create_form_schemas_and_responses

Revision ID: 5e62aa85e319
Revises: c7049ea7b006
Create Date: 2026-07-23 11:57:28.214434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e62aa85e319'
down_revision: Union[str, None] = 'c7049ea7b006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_schemas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_responses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('form_schema_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assignment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_schema_id'], ['form_schemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_assignments_document_id', table_name='assignments')
    op.drop_index('idx_assignments_reviewer_id', table_name='assignments')
    op.create_foreign_key(None, 'assignments', 'form_schemas', ['form_schema_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conflicts', 'documents', ['document_id'], ['id'])
    op.drop_constraint('documents_project_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'assignments', ['assignment_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('work_group_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_wgm_group', table_name='work_group_members')
    op.drop_index('idx_wgm_project_user', table_name='work_group_members')
    op.drop_constraint('uq_group_member', 'work_group_members', type_='unique')
    op.drop_constraint('work_group_members_added_by_fkey', 'work_group_members', type_='foreignkey')
    op.create_foreign_key(None, 'work_group_members', 'users', ['added_by'], ['id'])
    op.alter_column('work_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('work_groups_created_by_fkey', 'work_groups', type_='foreignkey')
    op.create_foreign_key(None, 'work_groups', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_groups', type_='foreignkey')
    op.create_foreign_key('work_groups_created_by_fkey', 'work_groups', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('work_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('work_groups', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_groups', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'work_group_members', type_='foreignkey')
    op.create_foreign_key('work_group_members_added_by_fkey', 'work_group_members', 'users', ['added_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_group_member', 'work_group_members', ['work_group_id', 'project_user_id'])
    op.create_index('idx_wgm_project_user', 'work_group_members', ['project_user_id'], unique=False)
    op.create_index('idx_wgm_group', 'work_group_members', ['work_group_id'], unique=False)
    op.alter_column('work_group_members', 'added_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_project_id_fkey', 'documents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'conflicts', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_index('idx_assignments_reviewer_id', 'assignments', ['reviewer_id'], unique=False)
    op.create_index('idx_assignments_document_id', 'assignments', ['document_id'], unique=False)
    op.drop_table('form_responses')
    op.drop_table('form_schemas')
    # ### end Alembic commands ###
